#!/usr/bin/env bash
#
# Dev helper: open a public HTTPS tunnel to the local API gateway (:8000) and
# write its URL into mobile/.env as EXPO_PUBLIC_API_URL, so the phone can reach
# the backend from ANY network (mobile data, a different Wi-Fi, an AP-isolated
# router) — no need for the phone to be on your Mac's LAN.
#
# Run this once per "session", and again any time the tunnel URL changes (e.g.
# after you fully restart your Mac, or if login starts hanging after a long
# sleep). Then restart Expo so it picks up the new URL:
#
#     ./scripts/dev-tunnel.sh
#     cd mobile && npx expo start --tunnel -c
#
# Requires cloudflared (install once with: brew install cloudflared).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOG="/tmp/cf-tunnel.log"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared is not installed. Run: brew install cloudflared"
  exit 1
fi

echo "Stopping any existing tunnel…"
pkill -f "cloudflared tunnel --url" 2>/dev/null || true
sleep 1

echo "Starting tunnel to http://localhost:8000 …"
rm -f "$LOG"
nohup cloudflared tunnel --url http://localhost:8000 >"$LOG" 2>&1 &
disown || true

URL=""
for _ in $(seq 1 60); do
  URL="$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$LOG" | head -1 || true)"
  [ -n "$URL" ] && break
  sleep 1
done

if [ -z "$URL" ]; then
  echo "Could not get a tunnel URL. Check $LOG"
  exit 1
fi

printf '# Auto-generated by scripts/dev-tunnel.sh — dev backend tunnel URL.\nEXPO_PUBLIC_API_URL=%s\n' "$URL" >"$ROOT/mobile/.env"

echo
echo "Tunnel URL : $URL"
echo "Wrote      : mobile/.env"
echo "Next       : cd mobile && npx expo start --tunnel -c"
