#!/usr/bin/env bash
#
# Dev helper: expose the local API gateway (:8000) on a public HTTPS URL so the
# phone can reach the backend from ANY network, and write that URL into
# mobile/.env as EXPO_PUBLIC_API_URL.
#
# It tries cloudflared first (clean, fast); if cloudflared's URL doesn't become
# reachable in time (TryCloudflare is occasionally flaky), it falls back to
# localtunnel. Run it whenever the tunnel URL changes (e.g. after a Mac restart,
# or if login starts hanging). Then restart Expo:
#
#     ./scripts/dev-tunnel.sh
#     cd mobile && npx expo start --tunnel -c
#
# Requires cloudflared (brew install cloudflared) and/or npx (for localtunnel).

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/mobile/.env"

reachable() {
  # $1 = base URL. True if GET $1/health returns 200 within the timeout.
  [ "$(curl -s -m 8 -o /dev/null -w '%{http_code}' "$1/health" 2>/dev/null)" = "200" ]
}

write_env() {
  printf '# Auto-generated by scripts/dev-tunnel.sh — dev backend tunnel URL.\nEXPO_PUBLIC_API_URL=%s\n' "$1" >"$ENV_FILE"
  echo
  echo "Tunnel URL : $1"
  echo "Wrote      : mobile/.env"
  echo "Next       : cd mobile && npx expo start --tunnel -c"
}

echo "Stopping any existing tunnels…"
pkill -f "cloudflared tunnel --url" 2>/dev/null || true
pkill -f "localtunnel --port" 2>/dev/null || true
pkill -f "lt --port" 2>/dev/null || true
sleep 1

# --- 1. Try cloudflared ----------------------------------------------------
if command -v cloudflared >/dev/null 2>&1; then
  echo "Trying cloudflared…"
  LOG="/tmp/cf-tunnel.log"; rm -f "$LOG"
  nohup cloudflared tunnel --url http://localhost:8000 >"$LOG" 2>&1 & disown || true
  URL=""
  for _ in $(seq 1 20); do
    URL="$(grep -oE 'https://[a-z0-9-]+\.trycloudflare\.com' "$LOG" | head -1 || true)"
    [ -n "$URL" ] && break
    sleep 1
  done
  if [ -n "$URL" ]; then
    echo "  got $URL — checking it routes…"
    for _ in $(seq 1 8); do reachable "$URL" && { write_env "$URL"; exit 0; }; sleep 3; done
    echo "  cloudflared URL didn't become reachable; falling back."
    pkill -f "cloudflared tunnel --url" 2>/dev/null || true
  fi
fi

# --- 2. Fall back to localtunnel -------------------------------------------
echo "Trying localtunnel…"
LOG="/tmp/lt.log"; rm -f "$LOG"
nohup npx --yes localtunnel --port 8000 >"$LOG" 2>&1 & disown || true
URL=""
for _ in $(seq 1 30); do
  URL="$(grep -oE 'https://[a-z0-9-]+\.loca\.lt' "$LOG" | head -1 || true)"
  [ -n "$URL" ] && break
  sleep 1
done
if [ -n "$URL" ]; then
  for _ in $(seq 1 6); do reachable "$URL" && { write_env "$URL"; exit 0; }; sleep 3; done
fi

echo "Could not establish a working tunnel. Check /tmp/cf-tunnel.log and /tmp/lt.log."
exit 1
