/**
 * PDF generation for statements + single-transaction receipts.
 *
 * We render an HTML string and hand it to expo-print, which produces a real PDF
 * file; expo-sharing then opens the share sheet so the user can "Save to Files",
 * AirDrop, email it, etc. Keeping it as HTML means the layout is easy to style.
 */
import { Platform } from 'react-native';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
// SDK 54 moved these file ops to the legacy entry point (the new default API is
// the File/Directory classes, which don't expose the Storage Access Framework).
import {
  EncodingType,
  StorageAccessFramework as SAF,
  readAsStringAsync,
  writeAsStringAsync,
} from 'expo-file-system/legacy';

import { type StatementEntry, type User, type Wallet } from './api';
import { currencyMeta } from './currencies';
import { formatDateTime, formatMoney, humanize, statementTitle } from './format';

const BRAND = '#5A4FF3';

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' })[c] as string,
  );
}

function shell(title: string, body: string): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    * { box-sizing: border-box; font-family: -apple-system, Roboto, 'Helvetica Neue', sans-serif; }
    body { margin: 0; padding: 32px; color: #16162E; }
    .brand { color: ${BRAND}; font-weight: 800; font-size: 22px; letter-spacing: -0.5px; }
    .muted { color: #6B6E86; }
    .title { font-size: 26px; font-weight: 800; margin: 4px 0 2px; }
    h1,h2,h3 { margin: 0; }
    .head { display: flex; justify-content: space-between; align-items: flex-start;
            border-bottom: 2px solid #E8E9F3; padding-bottom: 16px; margin-bottom: 20px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px;
         color: #9A9DB5; border-bottom: 1px solid #E8E9F3; padding: 8px 6px; }
    td { padding: 10px 6px; border-bottom: 1px solid #F0F1F8; font-size: 13px; }
    .right { text-align: right; }
    .credit { color: #0FB985; font-weight: 700; }
    .debit { color: #16162E; font-weight: 700; }
    .row { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #F0F1F8; }
    .row .k { color: #6B6E86; } .row .v { font-weight: 600; }
    .amount { font-size: 40px; font-weight: 800; letter-spacing: -1px; margin: 8px 0; }
    .pill { display:inline-block; padding: 3px 10px; border-radius: 999px; background:#F0F1F8; font-size:12px; font-weight:600; }
    .foot { margin-top: 28px; color:#9A9DB5; font-size: 11px; text-align:center; }
  </style></head><body>${body}
  <div class="foot">Generated by SecurePay · ${esc(formatDateTime(new Date().toISOString()))}</div>
  </body></html>`;
}

/** Full statement PDF for a date range. */
export function buildStatementHtml(
  entries: StatementEntry[],
  user: User | undefined,
  wallet: Wallet | undefined,
  rangeLabel: string,
): string {
  const cur = wallet?.currency ?? 'USD';
  let credits = 0;
  let debits = 0;
  const rows = entries
    .map((e) => {
      const amt = Number(e.amount);
      if (e.direction === 'credit') credits += amt;
      else debits += amt;
      const sign = e.direction === 'credit' ? '+' : '−';
      return `<tr>
        <td>${esc(formatDateTime(e.created_at))}</td>
        <td>${esc(statementTitle(e))}${e.counterparty_wallet_id ? ` <span class="muted">· #${e.counterparty_wallet_id}</span>` : ''}</td>
        <td>${esc(humanize(e.transaction_type))}</td>
        <td class="right ${e.direction}">${sign}${esc(formatMoney(e.amount, e.currency))}</td>
      </tr>`;
    })
    .join('');

  const body = `
    <div class="head">
      <div>
        <div class="brand">SecurePay</div>
        <div class="title">Account statement</div>
        <div class="muted">${esc(rangeLabel)}</div>
      </div>
      <div class="right">
        <div style="font-weight:700">${esc(user ? `${user.first_name} ${user.last_name}` : '')}</div>
        <div class="muted">${esc(user?.email ?? '')}</div>
        <div class="muted">Wallet #${wallet?.id ?? '—'} · ${esc(cur)}</div>
      </div>
    </div>
    <table>
      <thead><tr><th>Date</th><th>Details</th><th>Type</th><th class="right">Amount</th></tr></thead>
      <tbody>${rows || `<tr><td colspan="4" class="muted">No transactions in this range.</td></tr>`}</tbody>
    </table>
    <table style="margin-top:20px; width: 260px; margin-left:auto;">
      <tr><td class="muted">Total in</td><td class="right credit">+${esc(formatMoney(credits, cur))}</td></tr>
      <tr><td class="muted">Total out</td><td class="right debit">−${esc(formatMoney(debits, cur))}</td></tr>
      <tr><td class="muted">Transactions</td><td class="right">${entries.length}</td></tr>
    </table>`;
  return shell('Statement', body);
}

/** Single-transaction receipt PDF. */
export function buildReceiptHtml(e: StatementEntry, user: User | undefined): string {
  const sign = e.direction === 'credit' ? '+' : '−';
  const crossCurrency = !!e.from_currency && e.from_currency !== e.to_currency;
  const rows: [string, string][] = [
    ['Status', humanize(e.status)],
    ['Type', humanize(e.transaction_type)],
    [e.direction === 'credit' ? 'From' : 'To', e.counterparty_name ?? '—'],
  ];
  if (e.counterparty_wallet_id) rows.push(['Wallet number', `#${e.counterparty_wallet_id}`]);
  rows.push(['Reference', `TXN-${e.id}`]);
  rows.push(['Date', formatDateTime(e.created_at)]);
  if (e.completed_at) rows.push(['Completed', formatDateTime(e.completed_at)]);
  if (e.description) rows.push(['Note', e.description]);
  if (crossCurrency && e.from_amount && e.to_amount) {
    rows.push(['Sent', formatMoney(e.from_amount, e.from_currency!)]);
    rows.push(['Received', formatMoney(e.to_amount, e.to_currency!)]);
    rows.push(['Exchange rate', `1 ${e.from_currency} = ${Number(e.exchange_rate).toFixed(4)} ${e.to_currency}`]);
  }

  const body = `
    <div class="head">
      <div><div class="brand">SecurePay</div><div class="title">Receipt</div></div>
      <div class="right muted">${esc(user ? `${user.first_name} ${user.last_name}` : '')}</div>
    </div>
    <div style="text-align:center; padding: 8px 0 16px;">
      <div class="muted">${e.direction === 'credit' ? 'Received' : 'Sent'}</div>
      <div class="amount ${e.direction}">${sign}${esc(formatMoney(e.amount, e.currency))}</div>
      <span class="pill">${esc(humanize(e.status))}</span>
    </div>
    ${rows.map(([k, v]) => `<div class="row"><span class="k">${esc(k)}</span><span class="v">${esc(v)}</span></div>`).join('')}`;
  return shell('Receipt', body);
}

export type SaveResult = 'saved' | 'shared' | 'cancelled';

async function share(uri: string, fileName: string): Promise<SaveResult> {
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: fileName,
      UTI: 'com.adobe.pdf',
    });
    return 'shared';
  }
  return 'cancelled';
}

/**
 * Render `html` to a PDF and let the user keep it.
 *  - Android: open the system folder picker and write the file there (a real
 *    "download" to e.g. Downloads). Falls back to the share sheet if they cancel.
 *  - iOS: the share sheet, whose "Save to Files" is the native way to save.
 */
export async function savePdf(html: string, fileName: string): Promise<SaveResult> {
  const { uri } = await Print.printToFileAsync({ html });

  if (Platform.OS === 'android') {
    const perm = await SAF.requestDirectoryPermissionsAsync();
    if (!perm.granted) return share(uri, fileName); // user backed out of the picker
    const base64 = await readAsStringAsync(uri, { encoding: EncodingType.Base64 });
    const destUri = await SAF.createFileAsync(
      perm.directoryUri,
      fileName.replace(/\.pdf$/i, ''),
      'application/pdf',
    );
    await writeAsStringAsync(destUri, base64, { encoding: EncodingType.Base64 });
    return 'saved';
  }

  return share(uri, fileName);
}
